version: '3.7'

volumes:
  shorts-bot:    

services:
  node-bot:
    build: ./
    container_name: shorts-bot
    command: npm run start
    environment:
      POST: "${POST}"
      GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials.json"
    volumes:
      - shorts-bot:/app/output
      - ${CREDENTIALS_VOLUME}:/app/credentials.json